#!/bin/sh
yad \
--icons \
--text="Here are configuration apps that may be not obvious, other settings might be in Settings app or try searching for them" \
--read-dir="./functions/settings/settingsfunctions" \
--title="UFlinux Advanced Settings" \
--width=860 \
--height=600 \
--no-buttons \
--single-click \
