#!/bin/sh
if [ -f "locale/$LANG" ]
then
. "locale/$LANG"
else
. "locale/en_US.UTF-8"
 echo "$LANG was not found, loading en_US.UTF-8"
fi
yad \
--icons \
--read-dir="./functions/developer/developerfunctions" \
--title="$L_DEVHELPER" \
--width=860 \
--height=600 \
--no-buttons \
--single-click \
