#!/bin/sh
fwupdmgr --force refresh
lsmod | grep nouveau
if  [ "$?" -eq "0" ]
then
	if zenity --question --width 440 --text="NVIDIA GPU detected, would you like to install NVIDIA driver? \n without NVIDIA driver expect graphical glitches, low performance and non-functioning apps \n If you are in LIVE enviroment do not install install it, simply install OS and then install driver"
	then
		sh /usr/share/ufhelper/functions/hardware/hardwarefunctions/nvidia.sh	
	fi
fi
